---
- hosts: bonchvisor14
  remote_user: cephadmin
  become: true
  become_user: root
  become_method: sudo
  vars:
   disk:
     - sdb
     - sdc
     - sdd
     - sde

  tasks:

   - name: Detect used service
     shell: systemctl list-units --type=service --all | grep ceph | grep running | awk '{print $1}'
     args:
       executable: /bin/bash
       warn: false
     register: services

   - name: Restart all services
     shell: systemctl restart {{item}}
     args:
       executable: /bin/bash
       warn: false
     loop: "{{services.stdout_lines}}"
     when: services.stdout != ""
