---
- hosts: bonchvisors
  serial: 1
  remote_user: cephadmin
  become: true
  become_user: root
  become_method: sudo
  vars:
   disk:
     - sdb
     - sdc
     - sdd
   dbpart:
     - sde1
     - sde2
     - sde3

  tasks:

#    - name: list variables
#      debug:
#       msg: ceph-volume lvm create --bluestore --data /dev/{{disk[index]}} --block.db /dev/{{dbpart[index]}}
#      loop: "{{ disk|flatten(levels=1) }}"
#      loop_control:
#       index_var: index

#    - name: wipe HDD
#      shell: wipefs -a /dev/{{item}}
#      args:
#       executable: /bin/bash
#      with_items: "{{ disk }}"

    - name: create OSD on hosts
      shell: ceph-volume lvm create --bluestore --data /dev/{{disk[index]}} --block.db /dev/{{dbpart[index]}}
      args:
       executable: /bin/bash
      loop: "{{ disk|flatten(levels=1) }}"
      loop_control:
       index_var: index
