---
- hosts: controllers
  remote_user: cephadmin
  become: true
  become_user: root
  become_method: sudo

  tasks:

    - name: Add hosts entry
      lineinfile:
       path: /etc/hosts
       line: "{{ item.hosts }}"
      with_items:
       - { hosts: '172.17.2.54 bonchvisor04' }
       - { hosts: '172.17.2.55 bonchvisor05' }
       - { hosts: '172.17.2.56 bonchvisor06' }
       - { hosts: '172.17.2.57 bonchvisor07' }
       - { hosts: '172.17.2.58 bonchvisor08' }
       - { hosts: '172.17.2.59 bonchvisor09' }
       - { hosts: '172.17.2.60 bonchvisor10' }
       - { hosts: '172.17.2.61 bonchvisor11' }
       - { hosts: '172.17.2.62 bonchvisor12' }
       - { hosts: '172.17.3.50 controller-ceph' }
       - { hosts: '172.17.3.100 controller-virt' }
       - { hosts: '172.17.3.200 controller-net' }

