---
- hosts: bonchvisors
  remote_user: cephadmin
  become: true
  become_user: root
  become_method: sudo

  tasks:

#  - name: install openstack nova compute elements
#    yum:
#     name: "{{ packages }}"
#     state: latest
#    vars:
#     packages:
#     - openstack-neutron-linuxbridge
#     - ebtables
#     - ipset
#     - openstack-nova-compute
#     - openstack-neutron-ml2
#     - openstack-neutron-openvswitch


#  - name: restart openvswitch services
#    systemd:
#     state: restarted
#     enabled: yes
#     daemon_reload: yes
#     name: openvswitch.service

  - name: get public ip address
    shell: echo 172.17.2.$((50+$(echo $HOSTNAME | awk -F "bonchvisor" '{print $2}' | sed 's/^0*//')))
    args:
     executable: /bin/bash
    register: public_ip

  - name: get private ip address
    shell: echo 172.17.3.$((50+$(echo $HOSTNAME | awk -F "bonchvisor" '{print $2}' | sed 's/^0*//')))
    args:
     executable: /bin/bash
    register: private_ip

  - name: get first interface name
    shell: "ip a | grep enp | awk 'NR==1{print $2}' | tr -d :"
    args:
     executable: /bin/bash
    register: firstport

  - name: get second interface name
    shell: "ip a | grep enp | awk 'NR==2{print $2}' | tr -d :"
    args:
     executable: /bin/bash
    register: secondport

  - name: collect old ifcfg-files
    shell: ls /etc/sysconfig/network-scripts/ | grep ifcfg | grep -v 'ifcfg-lo\|ifcfg-ens1f0\|ens1f1' | awk '{print $1}'
    args:
     executable: /bin/bash
    register: oldint

  - name: delete old interface files
    file:
     state: absent
     path: /etc/sysconfig/network-scripts/{{ item }}
    loop: "{{oldint.stdout_lines}}"
    when: oldint.stdout != ""

  - name: cretae ifcfg-{{ firstport.stdout }} network config file
    template:
     src: /etc/ansible/files/networks/ifcfg-physicalif01
     dest: /etc/sysconfig/network-scripts/ifcfg-{{ firstport.stdout }}
     owner: root
     group: root
     mode: 0644    

  - name: cretae ifcfg-{{ secondport.stdout }} network config file
    template:
     src: /etc/ansible/files/networks/ifcfg-physicalif02
     dest: /etc/sysconfig/network-scripts/ifcfg-{{ secondport.stdout }}
     owner: root
     group: root
     mode: 0644

  - name: cretae bond0 network config file
    template:
     src: /etc/ansible/files/networks/ifcfg-bond0
     dest: /etc/sysconfig/network-scripts/ifcfg-bond0
     owner: root
     group: root
     mode: 0644

  - name: cretae main bridge network config file
    template:
     src: /etc/ansible/files/networks/ifcfg-br-ext-main
     dest: /etc/sysconfig/network-scripts/ifcfg-br-ext-main
     owner: root
     group: root
     mode: 0644

  - name: cretae mgmt0 network config file
    template:
     src: /etc/ansible/files/networks/ifcfg-mgmt0
     dest: /etc/sysconfig/network-scripts/ifcfg-mgmt0
     owner: root
     group: root
     mode: 0644

  - name: create internal port config file
    template:
     src: /etc/ansible/files/networks/ifcfg-port-int
     dest: /etc/sysconfig/network-scripts/ifcfg-port-int
     owner: root
     group: root
     mode: 0644

#  - name: creat first externalbridge patchpanel network config file
#    template:
#     src: /etc/ansible/files/networks/ifcfg-patch-main-ext01
#     dest: /etc/sysconfig/network-scripts/ifcfg-patch-main-ext01
#     owner: root
#     group: root
#     mode: 0644


#  - name: creat second external bridge patchpanel network config file
#    template:
#     src: /etc/ansible/files/networks/ifcfg-patch-main-ext02
#     dest: /etc/sysconfig/network-scripts/ifcfg-patch-main-ext02
#     owner: root
#     group: root
#     mode: 0644

  - name: creat slave bridge patchpanel network config file
    template:
     src: /etc/ansible/files/networks/ifcfg-patch-main-slave
     dest: /etc/sysconfig/network-scripts/ifcfg-patch-main-slave
     owner: root
     group: root
     mode: 0644

  - name: create neutron config file
    template:
     src: /etc/ansible/files/openvswitch_agent.ini
     dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
     owner: root
     group: root
     mode: 0644

  - name: restart all network services and delete all ovs bridge
    shell: ls /etc/sysconfig/network-scripts/ | grep ifcfg | grep -v 'ifcfg-lo\|ifcfg-ens1f0\|ens1f1\|enp\|bond0' | awk '{print $1}' | sed 's/ifcfg-//g'| while read line; do ip link set dev $line down && ip link delete $line; done; ovs-vsctl list-br | awk "{print $1}" | while read line; do ovs-vsctl --if-exist del-br $line; done; systemctl restart network; systemctl restart network
    args:
     executable: /bin/bash


#slave bridge creation




#  - name: detect all bridges, except ovs-main
#    shell: ovs-vsctl list-br | grep -v "ovs-main" | awk "{print $1}"
#    args:
#     executable: /bin/bash
#    register: oldbridges

#  - name: clear all bridges, except ovs-main
#    shell: ovs-vsctl --if-exist del-br {{ item }}
#    args:
#     executable: /bin/bash
#    loop: "{{oldbridges.stdout_lines}}"
#    when: oldbridges.stdout != ""

  - name: create slave bridge
    shell: ovs-vsctl --may-exist add-br br-slave && ovs-vsctl set int br-slave mtu_request=9000
    args:
     executable: /bin/bash

  - name: create fake management bridge
    shell: ovs-vsctl --may-exist add-br br-mgmt-fake br-slave 162 && ovs-vsctl set int br-mgmt-fake mtu_request=9000
    args:
     executable: /bin/bash

  - name: create fake interconnect bridge
    shell: ovs-vsctl --may-exist add-br br-ic-fake br-slave 163 && ovs-vsctl set int br-ic-fake mtu_request=9000
    args:
     executable: /bin/bash

  - name: create patchport -- br-slave to br-ext-main
    shell: ovs-vsctl --may-exist add-port br-slave patch-slave-main && ovs-vsctl set int patch-slave-main mtu_request=9000
    args:
     executable: /bin/bash

  - name: connect patchport -- br-slave to br-ext-main
    shell: ovs-vsctl set interface patch-slave-main type=patch options:peer=patch-main-slave
    args:
     executable: /bin/bash

  - name: create external bridge
    shell: ovs-vsctl --may-exist add-br br-ext && ovs-vsctl set int br-ext mtu_request=9000
    args:
     executable: /bin/bash

  - name: create patchport -- br-ext to br-ext-main
    shell: ovs-vsctl --may-exist add-port br-ext patch-ext-main && ovs-vsctl set int patch-ext-main mtu_request=8996
    args:
     executable: /bin/bash

  - name: connect patchport -- br-ext to br-ext-main
    shell: ovs-vsctl set interface patch-ext-main type=patch options:peer=patch-main-ext
    args:
     executable: /bin/bash

  - name: restart neutron-openvswitch
    systemd:
     state: restarted
     enabled: yes
     daemon_reload: yes
     name: neutron-openvswitch-agent.service

# postconfig
#
#  - name: set physical interface MTU
#    shell: ovs-vsctl set int {{ firstport.stdout }} mtu_request=9000 && ovs-vsctl set int {{ secondport.stdout }} mtu_request=9000
#    args:
#     executable: /bin/bash
