---
- hosts: bonchvisors
  remote_user: cephadmin
  become: true
  become_user: root
  become_method: sudo

  tasks:

  - name: install openstack nova compute elements
    yum:
     name: "{{ packages }}"
     state: latest
    vars:
     packages:
     - ebtables
     - ipset
     - openstack-nova-compute
     - openstack-neutron-ml2
     - openstack-neutron-openvswitch


#  - name: restart openvswitch services
#    systemd:
#     state: restarted
#     enabled: yes
#     daemon_reload: yes
#     name: openvswitch.service

  - name: get public ip address
    shell: echo 172.17.2.$((50+$(echo $HOSTNAME | awk -F "bonchvisor" '{print $2}' | sed 's/^0*//')))
    args:
     executable: /bin/bash
    register: public_ip

  - name: get private ip address
    shell: echo 172.17.3.$((50+$(echo $HOSTNAME | awk -F "bonchvisor" '{print $2}' | sed 's/^0*//')))
    args:
     executable: /bin/bash
    register: private_ip

  - name: get tunnel ip address
    shell: echo 172.17.1.$((50+$(echo $HOSTNAME | awk -F "bonchvisor" '{print $2}' | sed 's/^0*//')))
    args:
     executable: /bin/bash
    register: tunnel_ip


#  - name: creat first externalbridge patchpanel network config file
#    template:
#     src: /etc/ansible/files/networks/ifcfg-patch-main-ext01
#     dest: /etc/sysconfig/network-scripts/ifcfg-patch-main-ext01
#     owner: root
#     group: root
#     mode: 0644


#  - name: creat second external bridge patchpanel network config file
#    template:
#     src: /etc/ansible/files/networks/ifcfg-patch-main-ext02
#     dest: /etc/sysconfig/network-scripts/ifcfg-patch-main-ext02
#     owner: root
#     group: root
#     mode: 0644

  - name: create openvswitch_agent.ini config file
    template:
     src: /etc/ansible/files/openvswitch_agent.ini
     dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
     owner: root
     group: root
     mode: 0644


  - name: create ml2_conf.ini config file
    template:
     src: /etc/ansible/files/ml2_conf.ini
     dest: /etc/neutron/plugins/ml2/ml2_conf.ini
     owner: root
     group: root
     mode: 0644

  - name: create nova.conf config file
    template:
     src: /etc/ansible/files/nova.conf
     dest: /etc/nova/nova.conf
     owner: root
     group: root
     mode: 0644

#slave bridge creation




#  - name: detect all bridges, except ovs-main
#    shell: ovs-vsctl list-br | grep -v "ovs-main" | awk "{print $1}"
#    args:
#     executable: /bin/bash
#    register: oldbridges

#  - name: clear all bridges, except ovs-main
#    shell: ovs-vsctl --if-exist del-br {{ item }}
#    args:
#     executable: /bin/bash
#    loop: "{{oldbridges.stdout_lines}}"
#    when: oldbridges.stdout != ""

  - name: restart neutron-openvswitch
    systemd:
     state: restarted
     enabled: yes
     daemon_reload: yes
     name: neutron-openvswitch-agent.service

  - name: restart openstack-nova
    systemd:
     state: restarted
     enabled: yes
     daemon_reload: yes
     name: openstack-nova-compute.service

