- hosts: {{ your hosts }}
  remote_user: {{ you users }}
  become: true
  become_user: root
  become_method: sudo

  tasks:

  - name: ensure a list of packages installed
    yum:
     name: centos-release-openstack-pike
     state: latest

  - name: upgrade all packages
    yum:
     name: '*'
     state: latest


  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
     - python-openstackclient
     - openstack-selinux
